# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Team7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Team7
  pod 'Alamofire'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Analytics' 
  target 'iOS_Team7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_Team7UITests' do
    # Pods for testing
  end

end
